#! /usr/bin/env node

import inquirer from "inquirer";

//computer will generate a random number

//user input for guessing number

//compare user input with computer generated number and show result

const randomNumber = Math.floor(Math.random() * 10 + 1); ;
const answers = await inquirer.prompt([
    {
        name: "usserGuessNumber",
        type: "number",
        message: "please guess a number:",
    },
]);

if(answers.usserGuessNumber === randomNumber){
     console.log("congratulations you guessed right number");
}

else{
    console.log("you guessed wrong number");
}
