var myname = "Maliha iqbal";
console.log(myname);
console.log(myname);
console.log(myname);
console.log(myname);
console.log(myname);
myname = "Maliha";
console.log(myname);
var pi = 3.142;
console.log(pi);
